
import { PracticePlanForm } from '@/components/practice-planner/practice-plan-form';

export default function PracticePlannerPage() {
  return (
    <div className="container mx-auto px-4 py-8 sm:px-6 lg:px-8">
      <header className="mb-8 text-center">
        <h1 className="text-4xl font-bold tracking-tight text-primary sm:text-5xl">AI Practice Planner</h1>
        <p className="mt-3 text-lg text-muted-foreground sm:mt-4">
          Get a personalized golf practice plan generated by our AI coach to target your weaknesses.
        </p>
      </header>
      <PracticePlanForm />
    </div>
  );
}
